### PR TITLE
Add "titleFn" for reactive column title rendering by custom functions.

### PR DESCRIPTION
**Pull request by VansonLeung**
Add "titleFn" for reactive column title rendering by custom functions.
"titleFn" will override "title".

Reference: #115  #232 

I just moved from ReactiveTables to meteor-tabular, because the former one does not support Server-side rendering fluently. Still lots of bugs there & one annoys me most was the strange disappearance of table subscriptions when trying to Subscribe to a Pub which shares the same collection with the Pub the table uses. I could track down a wrong onStop implementation of its very own homemade ReactiveTables.Publish function, but I just don't know how to fix that before I gave up to use aldeed/meteor-tabular.

Usage:

``` js
TabularTables.StampcardTableSettings = new Tabular.Table({
  name: 'Stampcards', collection: Stampcards, pub: "stampcards", responsive: true, autoWidth: false,
  limit: 10, order: [[7, 'desc']],
  changeSelector: function(selector, userId) { return GENERIC_TABULAR_SELECTOR(userId, selector) },
  columns: [
    {data: 'name', titleFn: () => {return TAPi18n.__('GenericSchema.name.label')} },
    {data: 'summary', titleFn: () => {return TAPi18n.__('GenericSchema.summary.label')} },
    {data: 'desc', titleFn: () => {return TAPi18n.__('GenericSchema.desc.label')} },
    {data: 'launched', titleFn: () => {return TAPi18n.__('GenericSchema.launched.label')}, render: (val, type, doc) => { return val ? TAPi18n.__(val) : '' } },
    {data: 'launch_date', titleFn: () => {return TAPi18n.__('GenericSchema.launch_date.label')}, render: (val, type, doc) => { return DATE_GENERIC(val) } },
    {data: 'expiry_date', titleFn: () => {return TAPi18n.__('GenericSchema.expiry_date.label')}, render: (val, type, doc) => { return DATE_GENERIC(val) } },
    {data: 'createdAt', titleFn: () => {return TAPi18n.__('created_at')}, render: (val, type, doc) => { return DATE_GENERIC(val) } },
    {data: 'modifiedAt', titleFn: () => {return TAPi18n.__('modified_at')}, render: (val, type, doc) => { return DATE_GENERIC(val) } },
    {data: 'owner', titleFn: () => {return TAPi18n.__('owner')}, render: (val, type, doc) => { var client = Clients.findOne({owner: val}); return _LINK(Clients, client._id, 'name'); }},
    //{data: 'removed', hidden: true, },
    //{data: 'removedAt', hidden: true, },
    {tmpl: Meteor.isClient && Template.tb_combo, tmplContext: (rowData) => { return _.extend(rowData, {collection: 'Stampcards'}); }},
  ]
});
```

### CODE REVIEW

**Comment by derouck** [comment]
@aldeed Would you consider merging this? I think it's really useful to be able to use i18n for column titles like this. The changes seem to be running fine at my end.

**Comment by aldeed** [comment]
Couldn't merge this due to all the other code but I added titleFn.

**Comment by thearabbit** [comment]
I tried but

**Comment by aldeed** [comment]
@thearabbit Submit a new issue about that please. Might have to tweak the way titleFn is implemented a little.

**Pull request closed without merging**
