### PR TITLE
Changes for issue #96 - only send _id field

### PR DESCRIPTION
**Pull request by guilhermedecampo**
https://github.com/aldeed/meteor-tabular/issues/96

### CODE REVIEW

**Comment by guilhermedecampo** [comment]
@aldeed what do you think?

**Comment by aldeed** [comment]
@guilhermedecampo first argument should still be `selector`.

**Comment by guilhermedecampo** [comment]
@aldeed now should be ok =)

**Comment by aldeed** [comment]
Thanks!

**Comment by guilhermedecampo** [comment]
Thank you for the package!

**Pull request merged**
